/********************************************************************************
** Form generated from reading UI file 'dialog.ui'
**
** Created by: Qt User Interface Compiler version 5.9.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_DIALOG_H
#define UI_DIALOG_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>

QT_BEGIN_NAMESPACE

class Ui_Dialog
{
public:
    QFrame *frame5_2;
    QLabel *textLabel2;
    QComboBox *comboxChannel;
    QFrame *frame6;
    QLabel *textLabel1_2;
    QLineEdit *EditPreSetNo;
    QPushButton *pushButSet;
    QPushButton *pushButPresetDel;
    QPushButton *pushButGotoPreset;
    QFrame *frame3;
    QLabel *IP;
    QLabel *Port;
    QLabel *PassWord;
    QLabel *UserName;
    QLineEdit *lineEdit4;
    QLineEdit *lineEdit3;
    QLineEdit *lineEdit1;
    QLineEdit *lineEdit2;
    QPushButton *Login;
    QPushButton *Logout;
    QFrame *frame7;
    QLabel *textLabel3;
    QLabel *textLabel2_2;
    QLineEdit *EditPresetNum;
    QLineEdit *AutoTourNo;
    QPushButton *ButStartTour;
    QPushButton *ButStopTour;
    QPushButton *ButAddTour;
    QPushButton *ButDelTourPreset;
    QPushButton *ButDelTourNo;
    QFrame *frame12;
    QLabel *textLabel5;
    QPushButton *ButLimitLeft;
    QPushButton *ButLimitRight;
    QPushButton *ButStartScan;
    QPushButton *butStopScan;
    QFrame *frame5;
    QLabel *textLabel1;
    QComboBox *comboxCtrlParam;
    QPushButton *pushButRightUP;
    QPushButton *pushButRight;
    QPushButton *pushButRDown;
    QPushButton *pushButDZoom;
    QPushButton *pushButDFocus;
    QPushButton *pushButDAperture;
    QPushButton *pushButLeft;
    QPushButton *pushButLeftDown;
    QPushButton *pushButAZoom;
    QPushButton *pushButAFocus;
    QPushButton *pushButAperture;
    QPushButton *pushButDown;
    QPushButton *pushButLeftUp;
    QPushButton *pushButUp;
    QFrame *frame14;
    QLabel *textLabel10;
    QLabel *textLabel9;
    QLabel *textLabel8;
    QLabel *textLabel7;
    QLineEdit *lineEditX;
    QLineEdit *lineEditY;
    QLineEdit *lineEditZoom;
    QPushButton *ButSIT;
    QFrame *frame13;
    QLabel *textLabel6;
    QPushButton *ButStartPan;
    QPushButton *ButStopPan;
    QFrame *frame15;
    QLabel *textLabel11;
    QComboBox *comboxAuxNo;
    QPushButton *ButOpenAUX;
    QPushButton *ButCloseAUX;
    QFrame *frame10;
    QLabel *textLabel4;
    QLineEdit *PattermNo;
    QPushButton *ButStartProgram;
    QPushButton *ButStopProgram;
    QPushButton *ButStartPatterm;
    QPushButton *ButStopPatterm;
    QPushButton *ButDelPatterm;
    QFrame *frame14_2;
    QLabel *textLabel1_3;
    QPushButton *ButMenuLeft;
    QPushButton *ButMenuUP;
    QPushButton *ButMenuDown;
    QPushButton *ButMenuRight;
    QPushButton *ButOpenMenu;
    QPushButton *ButCloseMenu;
    QPushButton *ButMenuOK;
    QPushButton *ButMenuCancel;

    void setupUi(QDialog *Dialog)
    {
        if (Dialog->objectName().isEmpty())
            Dialog->setObjectName(QStringLiteral("Dialog"));
        Dialog->setEnabled(true);
        Dialog->resize(895, 400);
        Dialog->setMinimumSize(QSize(895, 400));
        Dialog->setMaximumSize(QSize(895, 400));
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(85, 170, 255, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(212, 234, 255, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(148, 202, 255, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(42, 85, 127, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(57, 113, 170, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        QBrush brush6(QColor(255, 255, 255, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush6);
        QBrush brush7(QColor(212, 228, 255, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush8(QColor(0, 0, 128, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Highlight, brush8);
        palette.setBrush(QPalette::Active, QPalette::HighlightedText, brush6);
        palette.setBrush(QPalette::Active, QPalette::Link, brush);
        palette.setBrush(QPalette::Active, QPalette::LinkVisited, brush);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        QBrush brush9(QColor(123, 189, 255, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Highlight, brush8);
        palette.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush6);
        QBrush brush10(QColor(0, 0, 255, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Inactive, QPalette::Link, brush10);
        QBrush brush11(QColor(255, 0, 255, 255));
        brush11.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Inactive, QPalette::LinkVisited, brush11);
        QBrush brush12(QColor(128, 128, 128, 255));
        brush12.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush9);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Highlight, brush8);
        palette.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::Link, brush10);
        palette.setBrush(QPalette::Disabled, QPalette::LinkVisited, brush11);
        Dialog->setPalette(palette);
        frame5_2 = new QFrame(Dialog);
        frame5_2->setObjectName(QStringLiteral("frame5_2"));
        frame5_2->setGeometry(QRect(10, 89, 251, 41));
        frame5_2->setFrameShape(QFrame::StyledPanel);
        frame5_2->setFrameShadow(QFrame::Plain);
        textLabel2 = new QLabel(frame5_2);
        textLabel2->setObjectName(QStringLiteral("textLabel2"));
        textLabel2->setGeometry(QRect(10, 10, 91, 21));
        textLabel2->setWordWrap(false);
        comboxChannel = new QComboBox(frame5_2);
        comboxChannel->setObjectName(QStringLiteral("comboxChannel"));
        comboxChannel->setGeometry(QRect(103, 10, 140, 22));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Active, QPalette::Highlight, brush8);
        palette1.setBrush(QPalette::Active, QPalette::HighlightedText, brush6);
        palette1.setBrush(QPalette::Active, QPalette::Link, brush);
        palette1.setBrush(QPalette::Active, QPalette::LinkVisited, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Highlight, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Link, brush10);
        palette1.setBrush(QPalette::Inactive, QPalette::LinkVisited, brush11);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush9);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Highlight, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::Link, brush10);
        palette1.setBrush(QPalette::Disabled, QPalette::LinkVisited, brush11);
        comboxChannel->setPalette(palette1);
        frame6 = new QFrame(Dialog);
        frame6->setObjectName(QStringLiteral("frame6"));
        frame6->setGeometry(QRect(259, 89, 240, 80));
        frame6->setFrameShape(QFrame::StyledPanel);
        frame6->setFrameShadow(QFrame::Plain);
        textLabel1_2 = new QLabel(frame6);
        textLabel1_2->setObjectName(QStringLiteral("textLabel1_2"));
        textLabel1_2->setGeometry(QRect(10, 10, 81, 22));
        textLabel1_2->setWordWrap(false);
        EditPreSetNo = new QLineEdit(frame6);
        EditPreSetNo->setObjectName(QStringLiteral("EditPreSetNo"));
        EditPreSetNo->setGeometry(QRect(90, 10, 140, 22));
        pushButSet = new QPushButton(frame6);
        pushButSet->setObjectName(QStringLiteral("pushButSet"));
        pushButSet->setGeometry(QRect(11, 41, 70, 25));
        pushButPresetDel = new QPushButton(frame6);
        pushButPresetDel->setObjectName(QStringLiteral("pushButPresetDel"));
        pushButPresetDel->setGeometry(QRect(87, 41, 71, 25));
        pushButGotoPreset = new QPushButton(frame6);
        pushButGotoPreset->setObjectName(QStringLiteral("pushButGotoPreset"));
        pushButGotoPreset->setGeometry(QRect(160, 40, 71, 25));
        frame3 = new QFrame(Dialog);
        frame3->setObjectName(QStringLiteral("frame3"));
        frame3->setGeometry(QRect(10, 10, 489, 80));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Active, QPalette::Highlight, brush8);
        palette2.setBrush(QPalette::Active, QPalette::HighlightedText, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Link, brush);
        palette2.setBrush(QPalette::Active, QPalette::LinkVisited, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Highlight, brush8);
        palette2.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Link, brush10);
        palette2.setBrush(QPalette::Inactive, QPalette::LinkVisited, brush11);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush9);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Highlight, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Link, brush10);
        palette2.setBrush(QPalette::Disabled, QPalette::LinkVisited, brush11);
        frame3->setPalette(palette2);
        frame3->setFrameShape(QFrame::StyledPanel);
        frame3->setFrameShadow(QFrame::Plain);
        IP = new QLabel(frame3);
        IP->setObjectName(QStringLiteral("IP"));
        IP->setGeometry(QRect(12, 10, 18, 22));
        IP->setWordWrap(false);
        Port = new QLabel(frame3);
        Port->setObjectName(QStringLiteral("Port"));
        Port->setGeometry(QRect(12, 41, 27, 22));
        Port->setWordWrap(false);
        PassWord = new QLabel(frame3);
        PassWord->setObjectName(QStringLiteral("PassWord"));
        PassWord->setGeometry(QRect(159, 41, 81, 22));
        PassWord->setWordWrap(false);
        UserName = new QLabel(frame3);
        UserName->setObjectName(QStringLiteral("UserName"));
        UserName->setGeometry(QRect(162, 10, 81, 22));
        UserName->setWordWrap(false);
        lineEdit4 = new QLineEdit(frame3);
        lineEdit4->setObjectName(QStringLiteral("lineEdit4"));
        lineEdit4->setGeometry(QRect(250, 10, 100, 22));
        lineEdit3 = new QLineEdit(frame3);
        lineEdit3->setObjectName(QStringLiteral("lineEdit3"));
        lineEdit3->setGeometry(QRect(250, 41, 100, 22));
        lineEdit1 = new QLineEdit(frame3);
        lineEdit1->setObjectName(QStringLiteral("lineEdit1"));
        lineEdit1->setGeometry(QRect(46, 10, 100, 22));
        lineEdit2 = new QLineEdit(frame3);
        lineEdit2->setObjectName(QStringLiteral("lineEdit2"));
        lineEdit2->setGeometry(QRect(45, 41, 100, 22));
        Login = new QPushButton(frame3);
        Login->setObjectName(QStringLiteral("Login"));
        Login->setGeometry(QRect(360, 10, 80, 25));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette3.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette3.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette3.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush);
        palette3.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette3.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Active, QPalette::Highlight, brush8);
        palette3.setBrush(QPalette::Active, QPalette::HighlightedText, brush6);
        palette3.setBrush(QPalette::Active, QPalette::Link, brush);
        palette3.setBrush(QPalette::Active, QPalette::LinkVisited, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        palette3.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette3.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette3.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Highlight, brush8);
        palette3.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::Link, brush10);
        palette3.setBrush(QPalette::Inactive, QPalette::LinkVisited, brush11);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::Midlight, brush9);
        palette3.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette3.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette3.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Highlight, brush8);
        palette3.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::Link, brush10);
        palette3.setBrush(QPalette::Disabled, QPalette::LinkVisited, brush11);
        Login->setPalette(palette3);
        Logout = new QPushButton(frame3);
        Logout->setObjectName(QStringLiteral("Logout"));
        Logout->setGeometry(QRect(360, 40, 80, 25));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette4.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette4.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette4.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush);
        palette4.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette4.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Active, QPalette::Highlight, brush8);
        palette4.setBrush(QPalette::Active, QPalette::HighlightedText, brush6);
        palette4.setBrush(QPalette::Active, QPalette::Link, brush);
        palette4.setBrush(QPalette::Active, QPalette::LinkVisited, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        palette4.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette4.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette4.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Highlight, brush8);
        palette4.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::Link, brush10);
        palette4.setBrush(QPalette::Inactive, QPalette::LinkVisited, brush11);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::Midlight, brush9);
        palette4.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette4.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette4.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette4.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Highlight, brush8);
        palette4.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::Link, brush10);
        palette4.setBrush(QPalette::Disabled, QPalette::LinkVisited, brush11);
        Logout->setPalette(palette4);
        frame7 = new QFrame(Dialog);
        frame7->setObjectName(QStringLiteral("frame7"));
        frame7->setGeometry(QRect(260, 170, 240, 224));
        frame7->setFrameShape(QFrame::StyledPanel);
        frame7->setFrameShadow(QFrame::Plain);
        frame7->setLineWidth(1);
        frame7->setMidLineWidth(0);
        textLabel3 = new QLabel(frame7);
        textLabel3->setObjectName(QStringLiteral("textLabel3"));
        textLabel3->setGeometry(QRect(10, 11, 71, 16));
        textLabel3->setWordWrap(false);
        textLabel2_2 = new QLabel(frame7);
        textLabel2_2->setObjectName(QStringLiteral("textLabel2_2"));
        textLabel2_2->setGeometry(QRect(10, 43, 81, 16));
        textLabel2_2->setWordWrap(false);
        EditPresetNum = new QLineEdit(frame7);
        EditPresetNum->setObjectName(QStringLiteral("EditPresetNum"));
        EditPresetNum->setGeometry(QRect(89, 11, 140, 22));
        AutoTourNo = new QLineEdit(frame7);
        AutoTourNo->setObjectName(QStringLiteral("AutoTourNo"));
        AutoTourNo->setGeometry(QRect(89, 39, 140, 22));
        ButStartTour = new QPushButton(frame7);
        ButStartTour->setObjectName(QStringLiteral("ButStartTour"));
        ButStartTour->setGeometry(QRect(79, 65, 150, 25));
        ButStopTour = new QPushButton(frame7);
        ButStopTour->setObjectName(QStringLiteral("ButStopTour"));
        ButStopTour->setGeometry(QRect(79, 94, 150, 25));
        ButAddTour = new QPushButton(frame7);
        ButAddTour->setObjectName(QStringLiteral("ButAddTour"));
        ButAddTour->setGeometry(QRect(78, 123, 150, 25));
        ButDelTourPreset = new QPushButton(frame7);
        ButDelTourPreset->setObjectName(QStringLiteral("ButDelTourPreset"));
        ButDelTourPreset->setGeometry(QRect(57, 152, 171, 25));
        ButDelTourNo = new QPushButton(frame7);
        ButDelTourNo->setObjectName(QStringLiteral("ButDelTourNo"));
        ButDelTourNo->setGeometry(QRect(78, 183, 150, 25));
        frame12 = new QFrame(Dialog);
        frame12->setObjectName(QStringLiteral("frame12"));
        frame12->setGeometry(QRect(498, 305, 200, 87));
        frame12->setFrameShape(QFrame::StyledPanel);
        frame12->setFrameShadow(QFrame::Plain);
        textLabel5 = new QLabel(frame12);
        textLabel5->setObjectName(QStringLiteral("textLabel5"));
        textLabel5->setGeometry(QRect(10, 3, 81, 21));
        textLabel5->setWordWrap(false);
        ButLimitLeft = new QPushButton(frame12);
        ButLimitLeft->setObjectName(QStringLiteral("ButLimitLeft"));
        ButLimitLeft->setGeometry(QRect(11, 21, 80, 23));
        ButLimitRight = new QPushButton(frame12);
        ButLimitRight->setObjectName(QStringLiteral("ButLimitRight"));
        ButLimitRight->setGeometry(QRect(98, 21, 91, 23));
        ButStartScan = new QPushButton(frame12);
        ButStartScan->setObjectName(QStringLiteral("ButStartScan"));
        ButStartScan->setGeometry(QRect(11, 50, 75, 23));
        butStopScan = new QPushButton(frame12);
        butStopScan->setObjectName(QStringLiteral("butStopScan"));
        butStopScan->setGeometry(QRect(108, 50, 81, 23));
        frame5 = new QFrame(Dialog);
        frame5->setObjectName(QStringLiteral("frame5"));
        frame5->setGeometry(QRect(10, 129, 250, 263));
        frame5->setFrameShape(QFrame::StyledPanel);
        frame5->setFrameShadow(QFrame::Plain);
        textLabel1 = new QLabel(frame5);
        textLabel1->setObjectName(QStringLiteral("textLabel1"));
        textLabel1->setGeometry(QRect(10, 10, 91, 21));
        textLabel1->setWordWrap(false);
        comboxCtrlParam = new QComboBox(frame5);
        comboxCtrlParam->setObjectName(QStringLiteral("comboxCtrlParam"));
        comboxCtrlParam->setGeometry(QRect(102, 10, 140, 22));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette5.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette5.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette5.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush);
        palette5.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette5.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette5.setBrush(QPalette::Active, QPalette::Highlight, brush8);
        palette5.setBrush(QPalette::Active, QPalette::HighlightedText, brush6);
        palette5.setBrush(QPalette::Active, QPalette::Link, brush);
        palette5.setBrush(QPalette::Active, QPalette::LinkVisited, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        palette5.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette5.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette5.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Highlight, brush8);
        palette5.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::Link, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::LinkVisited, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::Midlight, brush9);
        palette5.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette5.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette5.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette5.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::Highlight, brush8);
        palette5.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::Link, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::LinkVisited, brush);
        comboxCtrlParam->setPalette(palette5);
        pushButRightUP = new QPushButton(frame5);
        pushButRightUP->setObjectName(QStringLiteral("pushButRightUP"));
        pushButRightUP->setGeometry(QRect(159, 43, 81, 25));
        pushButRight = new QPushButton(frame5);
        pushButRight->setObjectName(QStringLiteral("pushButRight"));
        pushButRight->setGeometry(QRect(160, 70, 81, 25));
        pushButRDown = new QPushButton(frame5);
        pushButRDown->setObjectName(QStringLiteral("pushButRDown"));
        pushButRDown->setGeometry(QRect(160, 102, 95, 25));
        pushButDZoom = new QPushButton(frame5);
        pushButDZoom->setObjectName(QStringLiteral("pushButDZoom"));
        pushButDZoom->setGeometry(QRect(159, 132, 81, 25));
        pushButDFocus = new QPushButton(frame5);
        pushButDFocus->setObjectName(QStringLiteral("pushButDFocus"));
        pushButDFocus->setGeometry(QRect(159, 162, 81, 25));
        pushButDAperture = new QPushButton(frame5);
        pushButDAperture->setObjectName(QStringLiteral("pushButDAperture"));
        pushButDAperture->setGeometry(QRect(159, 192, 81, 25));
        pushButLeft = new QPushButton(frame5);
        pushButLeft->setObjectName(QStringLiteral("pushButLeft"));
        pushButLeft->setGeometry(QRect(9, 72, 91, 25));
        pushButLeftDown = new QPushButton(frame5);
        pushButLeftDown->setObjectName(QStringLiteral("pushButLeftDown"));
        pushButLeftDown->setGeometry(QRect(9, 102, 91, 25));
        pushButAZoom = new QPushButton(frame5);
        pushButAZoom->setObjectName(QStringLiteral("pushButAZoom"));
        pushButAZoom->setGeometry(QRect(9, 132, 91, 25));
        pushButAFocus = new QPushButton(frame5);
        pushButAFocus->setObjectName(QStringLiteral("pushButAFocus"));
        pushButAFocus->setGeometry(QRect(9, 163, 95, 25));
        pushButAperture = new QPushButton(frame5);
        pushButAperture->setObjectName(QStringLiteral("pushButAperture"));
        pushButAperture->setGeometry(QRect(9, 193, 95, 25));
        pushButDown = new QPushButton(frame5);
        pushButDown->setObjectName(QStringLiteral("pushButDown"));
        pushButDown->setGeometry(QRect(100, 102, 60, 25));
        pushButLeftUp = new QPushButton(frame5);
        pushButLeftUp->setObjectName(QStringLiteral("pushButLeftUp"));
        pushButLeftUp->setGeometry(QRect(9, 43, 91, 25));
        pushButUp = new QPushButton(frame5);
        pushButUp->setObjectName(QStringLiteral("pushButUp"));
        pushButUp->setGeometry(QRect(100, 43, 60, 25));
        frame14 = new QFrame(Dialog);
        frame14->setObjectName(QStringLiteral("frame14"));
        frame14->setGeometry(QRect(697, 124, 191, 140));
        frame14->setFrameShape(QFrame::StyledPanel);
        frame14->setFrameShadow(QFrame::Plain);
        textLabel10 = new QLabel(frame14);
        textLabel10->setObjectName(QStringLiteral("textLabel10"));
        textLabel10->setGeometry(QRect(7, 93, 51, 20));
        textLabel10->setWordWrap(false);
        textLabel9 = new QLabel(frame14);
        textLabel9->setObjectName(QStringLiteral("textLabel9"));
        textLabel9->setGeometry(QRect(21, 62, 37, 16));
        textLabel9->setWordWrap(false);
        textLabel8 = new QLabel(frame14);
        textLabel8->setObjectName(QStringLiteral("textLabel8"));
        textLabel8->setGeometry(QRect(20, 30, 37, 16));
        textLabel8->setWordWrap(false);
        textLabel7 = new QLabel(frame14);
        textLabel7->setObjectName(QStringLiteral("textLabel7"));
        textLabel7->setGeometry(QRect(20, 1, 70, 21));
        textLabel7->setWordWrap(false);
        lineEditX = new QLineEdit(frame14);
        lineEditX->setObjectName(QStringLiteral("lineEditX"));
        lineEditX->setGeometry(QRect(70, 32, 108, 22));
        lineEditY = new QLineEdit(frame14);
        lineEditY->setObjectName(QStringLiteral("lineEditY"));
        lineEditY->setGeometry(QRect(70, 57, 108, 22));
        lineEditZoom = new QLineEdit(frame14);
        lineEditZoom->setObjectName(QStringLiteral("lineEditZoom"));
        lineEditZoom->setGeometry(QRect(70, 82, 108, 22));
        ButSIT = new QPushButton(frame14);
        ButSIT->setObjectName(QStringLiteral("ButSIT"));
        ButSIT->setGeometry(QRect(70, 107, 108, 25));
        frame13 = new QFrame(Dialog);
        frame13->setObjectName(QStringLiteral("frame13"));
        frame13->setGeometry(QRect(697, 332, 191, 60));
        frame13->setFrameShape(QFrame::StyledPanel);
        frame13->setFrameShadow(QFrame::Plain);
        textLabel6 = new QLabel(frame13);
        textLabel6->setObjectName(QStringLiteral("textLabel6"));
        textLabel6->setGeometry(QRect(10, 5, 91, 20));
        textLabel6->setWordWrap(false);
        ButStartPan = new QPushButton(frame13);
        ButStartPan->setObjectName(QStringLiteral("ButStartPan"));
        ButStartPan->setGeometry(QRect(11, 25, 95, 25));
        ButStopPan = new QPushButton(frame13);
        ButStopPan->setObjectName(QStringLiteral("ButStopPan"));
        ButStopPan->setGeometry(QRect(102, 25, 85, 25));
        frame15 = new QFrame(Dialog);
        frame15->setObjectName(QStringLiteral("frame15"));
        frame15->setGeometry(QRect(697, 260, 191, 73));
        frame15->setFrameShape(QFrame::StyledPanel);
        frame15->setFrameShadow(QFrame::Plain);
        textLabel11 = new QLabel(frame15);
        textLabel11->setObjectName(QStringLiteral("textLabel11"));
        textLabel11->setGeometry(QRect(10, 10, 71, 21));
        textLabel11->setWordWrap(false);
        comboxAuxNo = new QComboBox(frame15);
        comboxAuxNo->setObjectName(QStringLiteral("comboxAuxNo"));
        comboxAuxNo->setGeometry(QRect(80, 11, 101, 20));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette6.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette6.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette6.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette6.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush);
        palette6.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette6.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette6.setBrush(QPalette::Active, QPalette::Highlight, brush8);
        palette6.setBrush(QPalette::Active, QPalette::HighlightedText, brush6);
        palette6.setBrush(QPalette::Active, QPalette::Link, brush);
        palette6.setBrush(QPalette::Active, QPalette::LinkVisited, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        palette6.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette6.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette6.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Highlight, brush8);
        palette6.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::Link, brush10);
        palette6.setBrush(QPalette::Inactive, QPalette::LinkVisited, brush11);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::Midlight, brush9);
        palette6.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette6.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette6.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette6.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::Highlight, brush8);
        palette6.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::Link, brush10);
        palette6.setBrush(QPalette::Disabled, QPalette::LinkVisited, brush11);
        comboxAuxNo->setPalette(palette6);
        ButOpenAUX = new QPushButton(frame15);
        ButOpenAUX->setObjectName(QStringLiteral("ButOpenAUX"));
        ButOpenAUX->setGeometry(QRect(9, 40, 85, 25));
        ButCloseAUX = new QPushButton(frame15);
        ButCloseAUX->setObjectName(QStringLiteral("ButCloseAUX"));
        ButCloseAUX->setGeometry(QRect(100, 40, 85, 25));
        frame10 = new QFrame(Dialog);
        frame10->setObjectName(QStringLiteral("frame10"));
        frame10->setGeometry(QRect(498, 124, 200, 182));
        frame10->setFrameShape(QFrame::StyledPanel);
        frame10->setFrameShadow(QFrame::Plain);
        textLabel4 = new QLabel(frame10);
        textLabel4->setObjectName(QStringLiteral("textLabel4"));
        textLabel4->setGeometry(QRect(6, 6, 71, 31));
        textLabel4->setWordWrap(false);
        PattermNo = new QLineEdit(frame10);
        PattermNo->setObjectName(QStringLiteral("PattermNo"));
        PattermNo->setGeometry(QRect(75, 11, 120, 22));
        ButStartProgram = new QPushButton(frame10);
        ButStartProgram->setObjectName(QStringLiteral("ButStartProgram"));
        ButStartProgram->setGeometry(QRect(71, 40, 120, 25));
        ButStopProgram = new QPushButton(frame10);
        ButStopProgram->setObjectName(QStringLiteral("ButStopProgram"));
        ButStopProgram->setGeometry(QRect(71, 68, 120, 25));
        ButStartPatterm = new QPushButton(frame10);
        ButStartPatterm->setObjectName(QStringLiteral("ButStartPatterm"));
        ButStartPatterm->setGeometry(QRect(70, 96, 120, 25));
        ButStopPatterm = new QPushButton(frame10);
        ButStopPatterm->setObjectName(QStringLiteral("ButStopPatterm"));
        ButStopPatterm->setGeometry(QRect(70, 124, 120, 25));
        ButDelPatterm = new QPushButton(frame10);
        ButDelPatterm->setObjectName(QStringLiteral("ButDelPatterm"));
        ButDelPatterm->setGeometry(QRect(70, 152, 120, 25));
        frame14_2 = new QFrame(Dialog);
        frame14_2->setObjectName(QStringLiteral("frame14_2"));
        frame14_2->setGeometry(QRect(498, 10, 390, 115));
        frame14_2->setFrameShape(QFrame::StyledPanel);
        frame14_2->setFrameShadow(QFrame::Plain);
        textLabel1_3 = new QLabel(frame14_2);
        textLabel1_3->setObjectName(QStringLiteral("textLabel1_3"));
        textLabel1_3->setGeometry(QRect(10, 10, 81, 31));
        textLabel1_3->setWordWrap(false);
        ButMenuLeft = new QPushButton(frame14_2);
        ButMenuLeft->setObjectName(QStringLiteral("ButMenuLeft"));
        ButMenuLeft->setGeometry(QRect(100, 40, 60, 25));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette7.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette7.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette7.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette7.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette7.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette7.setBrush(QPalette::Active, QPalette::Text, brush);
        palette7.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette7.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette7.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette7.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette7.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette7.setBrush(QPalette::Active, QPalette::Highlight, brush8);
        palette7.setBrush(QPalette::Active, QPalette::HighlightedText, brush6);
        palette7.setBrush(QPalette::Active, QPalette::Link, brush);
        palette7.setBrush(QPalette::Active, QPalette::LinkVisited, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette7.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        palette7.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette7.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette7.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Highlight, brush8);
        palette7.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::Link, brush10);
        palette7.setBrush(QPalette::Inactive, QPalette::LinkVisited, brush11);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette7.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::Midlight, brush9);
        palette7.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette7.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette7.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette7.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette7.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette7.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::Highlight, brush8);
        palette7.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush6);
        palette7.setBrush(QPalette::Disabled, QPalette::Link, brush10);
        palette7.setBrush(QPalette::Disabled, QPalette::LinkVisited, brush11);
        ButMenuLeft->setPalette(palette7);
        ButMenuUP = new QPushButton(frame14_2);
        ButMenuUP->setObjectName(QStringLiteral("ButMenuUP"));
        ButMenuUP->setGeometry(QRect(160, 10, 60, 25));
        ButMenuDown = new QPushButton(frame14_2);
        ButMenuDown->setObjectName(QStringLiteral("ButMenuDown"));
        ButMenuDown->setGeometry(QRect(160, 70, 60, 25));
        ButMenuRight = new QPushButton(frame14_2);
        ButMenuRight->setObjectName(QStringLiteral("ButMenuRight"));
        ButMenuRight->setGeometry(QRect(215, 40, 60, 25));
        ButOpenMenu = new QPushButton(frame14_2);
        ButOpenMenu->setObjectName(QStringLiteral("ButOpenMenu"));
        ButOpenMenu->setGeometry(QRect(289, 4, 98, 25));
        ButCloseMenu = new QPushButton(frame14_2);
        ButCloseMenu->setObjectName(QStringLiteral("ButCloseMenu"));
        ButCloseMenu->setGeometry(QRect(290, 31, 98, 25));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette8.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette8.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette8.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette8.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette8.setBrush(QPalette::Active, QPalette::Text, brush);
        palette8.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette8.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette8.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette8.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette8.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette8.setBrush(QPalette::Active, QPalette::Highlight, brush8);
        palette8.setBrush(QPalette::Active, QPalette::HighlightedText, brush6);
        palette8.setBrush(QPalette::Active, QPalette::Link, brush);
        palette8.setBrush(QPalette::Active, QPalette::LinkVisited, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette8.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        palette8.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette8.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette8.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette8.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette8.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette8.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Highlight, brush8);
        palette8.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush6);
        palette8.setBrush(QPalette::Inactive, QPalette::Link, brush10);
        palette8.setBrush(QPalette::Inactive, QPalette::LinkVisited, brush11);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette8.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::Midlight, brush9);
        palette8.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette8.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette8.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette8.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette8.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette8.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette8.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette8.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::Highlight, brush8);
        palette8.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush6);
        palette8.setBrush(QPalette::Disabled, QPalette::Link, brush10);
        palette8.setBrush(QPalette::Disabled, QPalette::LinkVisited, brush11);
        ButCloseMenu->setPalette(palette8);
        ButMenuOK = new QPushButton(frame14_2);
        ButMenuOK->setObjectName(QStringLiteral("ButMenuOK"));
        ButMenuOK->setGeometry(QRect(290, 58, 98, 25));
        ButMenuCancel = new QPushButton(frame14_2);
        ButMenuCancel->setObjectName(QStringLiteral("ButMenuCancel"));
        ButMenuCancel->setGeometry(QRect(291, 85, 98, 25));

        retranslateUi(Dialog);

        QMetaObject::connectSlotsByName(Dialog);
    } // setupUi

    void retranslateUi(QDialog *Dialog)
    {
        Dialog->setWindowTitle(QApplication::translate("Dialog", "PTZ", Q_NULLPTR));
        textLabel2->setText(QApplication::translate("Dialog", "Channel NO.", Q_NULLPTR));
        textLabel1_2->setText(QApplication::translate("Dialog", "Preset NO.", Q_NULLPTR));
        pushButSet->setText(QApplication::translate("Dialog", "Set", Q_NULLPTR));
        pushButPresetDel->setText(QApplication::translate("Dialog", "Delete", Q_NULLPTR));
        pushButGotoPreset->setText(QApplication::translate("Dialog", "Go To", Q_NULLPTR));
        IP->setText(QApplication::translate("Dialog", "IP", Q_NULLPTR));
        Port->setText(QApplication::translate("Dialog", "Port", Q_NULLPTR));
        PassWord->setText(QApplication::translate("Dialog", "PassWord", Q_NULLPTR));
        UserName->setText(QApplication::translate("Dialog", "UserName", Q_NULLPTR));
        lineEdit4->setText(QApplication::translate("Dialog", "admin", Q_NULLPTR));
        lineEdit3->setText(QApplication::translate("Dialog", "admin", Q_NULLPTR));
        lineEdit1->setText(QApplication::translate("Dialog", "10.7.4.23", Q_NULLPTR));
        lineEdit2->setText(QApplication::translate("Dialog", "37777", Q_NULLPTR));
        Login->setText(QApplication::translate("Dialog", "Login", Q_NULLPTR));
        Logout->setText(QApplication::translate("Dialog", "Logout", Q_NULLPTR));
        textLabel3->setText(QApplication::translate("Dialog", "Preset No", Q_NULLPTR));
        textLabel2_2->setText(QApplication::translate("Dialog", "AutoTour", Q_NULLPTR));
        ButStartTour->setText(QApplication::translate("Dialog", "Start Tour", Q_NULLPTR));
        ButStopTour->setText(QApplication::translate("Dialog", "Stop Tour", Q_NULLPTR));
        ButAddTour->setText(QApplication::translate("Dialog", "Add Preset To Tour", Q_NULLPTR));
        ButDelTourPreset->setText(QApplication::translate("Dialog", "Del Preset From Tour", Q_NULLPTR));
        ButDelTourNo->setText(QApplication::translate("Dialog", "Delete Tour NO.", Q_NULLPTR));
        textLabel5->setText(QApplication::translate("Dialog", "Auto Scan :", Q_NULLPTR));
        ButLimitLeft->setText(QApplication::translate("Dialog", "Left Limit", Q_NULLPTR));
        ButLimitRight->setText(QApplication::translate("Dialog", "Right Limit", Q_NULLPTR));
        ButStartScan->setText(QApplication::translate("Dialog", "Start", Q_NULLPTR));
        butStopScan->setText(QApplication::translate("Dialog", "Stop", Q_NULLPTR));
        textLabel1->setText(QApplication::translate("Dialog", "Ctrol Parm", Q_NULLPTR));
        comboxCtrlParam->clear();
        comboxCtrlParam->insertItems(0, QStringList()
         << QApplication::translate("Dialog", "1", Q_NULLPTR)
         << QApplication::translate("Dialog", "2", Q_NULLPTR)
         << QApplication::translate("Dialog", "3", Q_NULLPTR)
         << QApplication::translate("Dialog", "4", Q_NULLPTR)
         << QApplication::translate("Dialog", "5", Q_NULLPTR)
         << QApplication::translate("Dialog", "6", Q_NULLPTR)
         << QApplication::translate("Dialog", "7", Q_NULLPTR)
         << QApplication::translate("Dialog", "8", Q_NULLPTR)
        );
        pushButRightUP->setText(QApplication::translate("Dialog", "Right up", Q_NULLPTR));
        pushButRight->setText(QApplication::translate("Dialog", "Right", Q_NULLPTR));
        pushButRDown->setText(QApplication::translate("Dialog", "Right Down", Q_NULLPTR));
        pushButDZoom->setText(QApplication::translate("Dialog", "Zoom -", Q_NULLPTR));
        pushButDFocus->setText(QApplication::translate("Dialog", "Focus -", Q_NULLPTR));
        pushButDAperture->setText(QApplication::translate("Dialog", "Aperture -", Q_NULLPTR));
        pushButLeft->setText(QApplication::translate("Dialog", "Left", Q_NULLPTR));
        pushButLeftDown->setText(QApplication::translate("Dialog", "Left Down", Q_NULLPTR));
        pushButAZoom->setText(QApplication::translate("Dialog", "Zoom +", Q_NULLPTR));
        pushButAFocus->setText(QApplication::translate("Dialog", "Focus +", Q_NULLPTR));
        pushButAperture->setText(QApplication::translate("Dialog", "Aperture +", Q_NULLPTR));
        pushButDown->setText(QApplication::translate("Dialog", "Down", Q_NULLPTR));
        pushButLeftUp->setText(QApplication::translate("Dialog", "Left Up", Q_NULLPTR));
        pushButUp->setText(QApplication::translate("Dialog", "UP", Q_NULLPTR));
        textLabel10->setText(QApplication::translate("Dialog", "Zoom", Q_NULLPTR));
        textLabel9->setText(QApplication::translate("Dialog", "Y", Q_NULLPTR));
        textLabel8->setText(QApplication::translate("Dialog", "X", Q_NULLPTR));
        textLabel7->setText(QApplication::translate("Dialog", "SIT :", Q_NULLPTR));
        ButSIT->setText(QApplication::translate("Dialog", "SIT", Q_NULLPTR));
        textLabel6->setText(QApplication::translate("Dialog", "Auto Pan :", Q_NULLPTR));
        ButStartPan->setText(QApplication::translate("Dialog", "Start", Q_NULLPTR));
        ButStopPan->setText(QApplication::translate("Dialog", "Stop", Q_NULLPTR));
        textLabel11->setText(QApplication::translate("Dialog", "AUX NO.", Q_NULLPTR));
        comboxAuxNo->clear();
        comboxAuxNo->insertItems(0, QStringList()
         << QApplication::translate("Dialog", "23", Q_NULLPTR)
         << QApplication::translate("Dialog", "24", Q_NULLPTR)
         << QApplication::translate("Dialog", "27", Q_NULLPTR)
         << QApplication::translate("Dialog", "41", Q_NULLPTR)
         << QApplication::translate("Dialog", "43", Q_NULLPTR)
        );
        ButOpenAUX->setText(QApplication::translate("Dialog", "Open", Q_NULLPTR));
        ButCloseAUX->setText(QApplication::translate("Dialog", "Close", Q_NULLPTR));
        textLabel4->setText(QApplication::translate("Dialog", " Pattern", Q_NULLPTR));
        ButStartProgram->setText(QApplication::translate("Dialog", "Program Start", Q_NULLPTR));
        ButStopProgram->setText(QApplication::translate("Dialog", "Program Stop", Q_NULLPTR));
        ButStartPatterm->setText(QApplication::translate("Dialog", "Pattern Start", Q_NULLPTR));
        ButStopPatterm->setText(QApplication::translate("Dialog", "Pattern Stop", Q_NULLPTR));
        ButDelPatterm->setText(QApplication::translate("Dialog", "Delete", Q_NULLPTR));
        textLabel1_3->setText(QApplication::translate("Dialog", "PTZ Menu", Q_NULLPTR));
        ButMenuLeft->setText(QApplication::translate("Dialog", "Left", Q_NULLPTR));
        ButMenuUP->setText(QApplication::translate("Dialog", "UP", Q_NULLPTR));
        ButMenuDown->setText(QApplication::translate("Dialog", "Down", Q_NULLPTR));
        ButMenuRight->setText(QApplication::translate("Dialog", "Right", Q_NULLPTR));
        ButOpenMenu->setText(QApplication::translate("Dialog", "Open Menu", Q_NULLPTR));
        ButCloseMenu->setText(QApplication::translate("Dialog", "Close Menu", Q_NULLPTR));
        ButMenuOK->setText(QApplication::translate("Dialog", "OK", Q_NULLPTR));
        ButMenuCancel->setText(QApplication::translate("Dialog", "Cancel", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class Dialog: public Ui_Dialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_DIALOG_H
