/********************************************************************************
** Form generated from reading UI file 'dialog.ui'
**
** Created by: Qt User Interface Compiler version 5.9.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_DIALOG_H
#define UI_DIALOG_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDateTimeEdit>
#include <QtWidgets/QDialog>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>

QT_BEGIN_NAMESPACE

class Ui_Dialog
{
public:
    QFrame *frame4;
    QLabel *textLabel1;
    QLabel *textLabel3;
    QComboBox *ComboxChannelIn;
    QPushButton *ButAlarmInStart;
    QPushButton *ButAlarmInStop;
    QFrame *frame6;
    QLabel *textLabel2;
    QComboBox *ComboxChannelOut;
    QPushButton *ButAlarmOutStart;
    QPushButton *ButAlarmOutStop;
    QLabel *textLabel3_2;
    QFrame *frame3;
    QLabel *IP;
    QLabel *Port;
    QLabel *UserName;
    QLabel *PassWord;
    QLineEdit *lineEdit1;
    QLineEdit *lineEdit2;
    QLineEdit *lineEdit4;
    QPushButton *Logout;
    QPushButton *Login;
    QLineEdit *lineEdit3;
    QFrame *frame7;
    QLabel *textLabel4;
    QLabel *textLabel5;
    QPushButton *ButGetTime;
    QPushButton *ButSetTime;
    QDateTimeEdit *DVRdateTime;
    QFrame *frame8;
    QLabel *textLabel6;
    QLabel *textLabel7;
    QComboBox *ComboxDiskNo;
    QLabel *TextDiskInfo;
    QLabel *textLabel8;
    QComboBox *ComboxOperateType;
    QPushButton *ButDiskControl;
    QFrame *frame10;
    QPushButton *ButBoot;
    QPushButton *ButBoot_2;
    QFrame *frame9;
    QFrame *frame13;
    QPushButton *ButNUM0;
    QPushButton *ButNUM1;
    QPushButton *ButNUM2;
    QPushButton *ButNUM3;
    QPushButton *ButNUM4;
    QPushButton *ButNUM5;
    QPushButton *ButNUM6;
    QPushButton *ButNUM7;
    QPushButton *ButNUM8;
    QPushButton *ButNUM9;
    QPushButton *ButNUM10;
    QPushButton *ButNUM11;
    QPushButton *ButNUM12;
    QPushButton *ButNUM13;
    QPushButton *ButNUM14;
    QPushButton *ButNUM15;
    QPushButton *ButNUM16;
    QFrame *frame14;
    QPushButton *ButJmpDown;
    QPushButton *ButJmpUp;
    QPushButton *ButStop;
    QPushButton *ButNext;
    QPushButton *ButFast;
    QPushButton *ButPlay;
    QPushButton *ButSlow;
    QPushButton *ButPrew;
    QPushButton *ButRec;
    QFrame *frame15;
    QPushButton *ButEsc;
    QPushButton *ButFn1;
    QPushButton *ButFn2;
    QPushButton *ButSplit;
    QPushButton *ButOne;
    QPushButton *ButInfo;
    QPushButton *ButPower;
    QPushButton *ButAddr;
    QPushButton *ButNine;
    QFrame *frame16;
    QPushButton *ButEnter;
    QPushButton *ButUP;
    QPushButton *ButRight;
    QPushButton *ButLeft;
    QPushButton *ButDown;

    void setupUi(QDialog *Dialog)
    {
        if (Dialog->objectName().isEmpty())
            Dialog->setObjectName(QStringLiteral("Dialog"));
        Dialog->setEnabled(true);
        Dialog->resize(820, 420);
        QSizePolicy sizePolicy(QSizePolicy::Minimum, QSizePolicy::Preferred);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(Dialog->sizePolicy().hasHeightForWidth());
        Dialog->setSizePolicy(sizePolicy);
        Dialog->setMinimumSize(QSize(820, 420));
        Dialog->setMaximumSize(QSize(920, 420));
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(85, 170, 255, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(212, 234, 255, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(148, 202, 255, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(42, 85, 127, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(57, 113, 170, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        QBrush brush6(QColor(255, 255, 255, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush6);
        QBrush brush7(QColor(212, 228, 255, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush8(QColor(0, 0, 128, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Highlight, brush8);
        palette.setBrush(QPalette::Active, QPalette::HighlightedText, brush6);
        palette.setBrush(QPalette::Active, QPalette::Link, brush);
        palette.setBrush(QPalette::Active, QPalette::LinkVisited, brush);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        QBrush brush9(QColor(123, 189, 255, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Highlight, brush8);
        palette.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush6);
        QBrush brush10(QColor(0, 0, 255, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Inactive, QPalette::Link, brush10);
        QBrush brush11(QColor(255, 0, 255, 255));
        brush11.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Inactive, QPalette::LinkVisited, brush11);
        QBrush brush12(QColor(128, 128, 128, 255));
        brush12.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush9);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Highlight, brush8);
        palette.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::Link, brush10);
        palette.setBrush(QPalette::Disabled, QPalette::LinkVisited, brush11);
        Dialog->setPalette(palette);
        frame4 = new QFrame(Dialog);
        frame4->setObjectName(QStringLiteral("frame4"));
        frame4->setGeometry(QRect(10, 61, 400, 70));
        frame4->setFrameShape(QFrame::StyledPanel);
        frame4->setFrameShadow(QFrame::Plain);
        textLabel1 = new QLabel(frame4);
        textLabel1->setObjectName(QStringLiteral("textLabel1"));
        textLabel1->setGeometry(QRect(10, 4, 201, 20));
        textLabel1->setWordWrap(false);
        textLabel3 = new QLabel(frame4);
        textLabel3->setObjectName(QStringLiteral("textLabel3"));
        textLabel3->setGeometry(QRect(9, 31, 91, 31));
        textLabel3->setWordWrap(false);
        ComboxChannelIn = new QComboBox(frame4);
        ComboxChannelIn->setObjectName(QStringLiteral("ComboxChannelIn"));
        ComboxChannelIn->setGeometry(QRect(103, 33, 120, 22));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Active, QPalette::Highlight, brush8);
        palette1.setBrush(QPalette::Active, QPalette::HighlightedText, brush6);
        palette1.setBrush(QPalette::Active, QPalette::Link, brush);
        palette1.setBrush(QPalette::Active, QPalette::LinkVisited, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Highlight, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Link, brush10);
        palette1.setBrush(QPalette::Inactive, QPalette::LinkVisited, brush11);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush9);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Highlight, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::Link, brush10);
        palette1.setBrush(QPalette::Disabled, QPalette::LinkVisited, brush11);
        ComboxChannelIn->setPalette(palette1);
        ButAlarmInStart = new QPushButton(frame4);
        ButAlarmInStart->setObjectName(QStringLiteral("ButAlarmInStart"));
        ButAlarmInStart->setGeometry(QRect(231, 31, 80, 25));
        ButAlarmInStop = new QPushButton(frame4);
        ButAlarmInStop->setObjectName(QStringLiteral("ButAlarmInStop"));
        ButAlarmInStop->setGeometry(QRect(315, 31, 80, 25));
        frame6 = new QFrame(Dialog);
        frame6->setObjectName(QStringLiteral("frame6"));
        frame6->setGeometry(QRect(409, 61, 400, 70));
        frame6->setFrameShape(QFrame::StyledPanel);
        frame6->setFrameShadow(QFrame::Plain);
        textLabel2 = new QLabel(frame6);
        textLabel2->setObjectName(QStringLiteral("textLabel2"));
        textLabel2->setGeometry(QRect(10, 4, 201, 20));
        textLabel2->setWordWrap(false);
        ComboxChannelOut = new QComboBox(frame6);
        ComboxChannelOut->setObjectName(QStringLiteral("ComboxChannelOut"));
        ComboxChannelOut->setGeometry(QRect(98, 33, 120, 22));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Active, QPalette::Highlight, brush8);
        palette2.setBrush(QPalette::Active, QPalette::HighlightedText, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Link, brush);
        palette2.setBrush(QPalette::Active, QPalette::LinkVisited, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Highlight, brush8);
        palette2.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Link, brush10);
        palette2.setBrush(QPalette::Inactive, QPalette::LinkVisited, brush11);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush9);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Highlight, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Link, brush10);
        palette2.setBrush(QPalette::Disabled, QPalette::LinkVisited, brush11);
        ComboxChannelOut->setPalette(palette2);
        ButAlarmOutStart = new QPushButton(frame6);
        ButAlarmOutStart->setObjectName(QStringLiteral("ButAlarmOutStart"));
        ButAlarmOutStart->setGeometry(QRect(224, 32, 80, 25));
        ButAlarmOutStop = new QPushButton(frame6);
        ButAlarmOutStop->setObjectName(QStringLiteral("ButAlarmOutStop"));
        ButAlarmOutStop->setGeometry(QRect(307, 32, 80, 25));
        textLabel3_2 = new QLabel(frame6);
        textLabel3_2->setObjectName(QStringLiteral("textLabel3_2"));
        textLabel3_2->setGeometry(QRect(8, 31, 91, 31));
        textLabel3_2->setWordWrap(false);
        frame3 = new QFrame(Dialog);
        frame3->setObjectName(QStringLiteral("frame3"));
        frame3->setGeometry(QRect(10, 11, 800, 42));
        frame3->setFrameShape(QFrame::StyledPanel);
        frame3->setFrameShadow(QFrame::Plain);
        IP = new QLabel(frame3);
        IP->setObjectName(QStringLiteral("IP"));
        IP->setGeometry(QRect(5, 10, 18, 22));
        IP->setWordWrap(false);
        Port = new QLabel(frame3);
        Port->setObjectName(QStringLiteral("Port"));
        Port->setGeometry(QRect(123, 10, 27, 22));
        Port->setWordWrap(false);
        UserName = new QLabel(frame3);
        UserName->setObjectName(QStringLiteral("UserName"));
        UserName->setGeometry(QRect(246, 10, 81, 22));
        UserName->setWordWrap(false);
        PassWord = new QLabel(frame3);
        PassWord->setObjectName(QStringLiteral("PassWord"));
        PassWord->setGeometry(QRect(425, 10, 71, 22));
        PassWord->setWordWrap(false);
        lineEdit1 = new QLineEdit(frame3);
        lineEdit1->setObjectName(QStringLiteral("lineEdit1"));
        lineEdit1->setGeometry(QRect(29, 10, 80, 22));
        lineEdit2 = new QLineEdit(frame3);
        lineEdit2->setObjectName(QStringLiteral("lineEdit2"));
        lineEdit2->setGeometry(QRect(156, 10, 80, 22));
        lineEdit4 = new QLineEdit(frame3);
        lineEdit4->setObjectName(QStringLiteral("lineEdit4"));
        lineEdit4->setGeometry(QRect(332, 10, 80, 22));
        Logout = new QPushButton(frame3);
        Logout->setObjectName(QStringLiteral("Logout"));
        Logout->setGeometry(QRect(707, 7, 80, 25));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette3.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette3.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette3.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush);
        palette3.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette3.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Active, QPalette::Highlight, brush8);
        palette3.setBrush(QPalette::Active, QPalette::HighlightedText, brush6);
        palette3.setBrush(QPalette::Active, QPalette::Link, brush);
        palette3.setBrush(QPalette::Active, QPalette::LinkVisited, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        palette3.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette3.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette3.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Highlight, brush8);
        palette3.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::Link, brush10);
        palette3.setBrush(QPalette::Inactive, QPalette::LinkVisited, brush11);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::Midlight, brush9);
        palette3.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette3.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette3.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Highlight, brush8);
        palette3.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::Link, brush10);
        palette3.setBrush(QPalette::Disabled, QPalette::LinkVisited, brush11);
        Logout->setPalette(palette3);
        Login = new QPushButton(frame3);
        Login->setObjectName(QStringLiteral("Login"));
        Login->setGeometry(QRect(621, 7, 80, 25));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette4.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette4.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette4.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush);
        palette4.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette4.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Active, QPalette::Highlight, brush8);
        palette4.setBrush(QPalette::Active, QPalette::HighlightedText, brush6);
        palette4.setBrush(QPalette::Active, QPalette::Link, brush);
        palette4.setBrush(QPalette::Active, QPalette::LinkVisited, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        palette4.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette4.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette4.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Highlight, brush8);
        palette4.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::Link, brush10);
        palette4.setBrush(QPalette::Inactive, QPalette::LinkVisited, brush11);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::Midlight, brush9);
        palette4.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette4.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette4.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette4.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Highlight, brush8);
        palette4.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::Link, brush10);
        palette4.setBrush(QPalette::Disabled, QPalette::LinkVisited, brush11);
        Login->setPalette(palette4);
        lineEdit3 = new QLineEdit(frame3);
        lineEdit3->setObjectName(QStringLiteral("lineEdit3"));
        lineEdit3->setGeometry(QRect(510, 10, 80, 22));
        frame7 = new QFrame(Dialog);
        frame7->setObjectName(QStringLiteral("frame7"));
        frame7->setGeometry(QRect(10, 139, 301, 90));
        frame7->setFrameShape(QFrame::StyledPanel);
        frame7->setFrameShadow(QFrame::Plain);
        textLabel4 = new QLabel(frame7);
        textLabel4->setObjectName(QStringLiteral("textLabel4"));
        textLabel4->setGeometry(QRect(10, 5, 231, 20));
        textLabel4->setWordWrap(false);
        textLabel5 = new QLabel(frame7);
        textLabel5->setObjectName(QStringLiteral("textLabel5"));
        textLabel5->setGeometry(QRect(10, 36, 81, 21));
        textLabel5->setWordWrap(false);
        ButGetTime = new QPushButton(frame7);
        ButGetTime->setObjectName(QStringLiteral("ButGetTime"));
        ButGetTime->setGeometry(QRect(90, 60, 80, 25));
        ButSetTime = new QPushButton(frame7);
        ButSetTime->setObjectName(QStringLiteral("ButSetTime"));
        ButSetTime->setGeometry(QRect(210, 60, 80, 25));
        DVRdateTime = new QDateTimeEdit(frame7);
        DVRdateTime->setObjectName(QStringLiteral("DVRdateTime"));
        DVRdateTime->setGeometry(QRect(91, 35, 201, 22));
        frame8 = new QFrame(Dialog);
        frame8->setObjectName(QStringLiteral("frame8"));
        frame8->setGeometry(QRect(318, 139, 491, 90));
        frame8->setFrameShape(QFrame::StyledPanel);
        frame8->setFrameShadow(QFrame::Plain);
        textLabel6 = new QLabel(frame8);
        textLabel6->setObjectName(QStringLiteral("textLabel6"));
        textLabel6->setGeometry(QRect(18, 5, 121, 20));
        textLabel6->setMidLineWidth(3);
        textLabel6->setWordWrap(false);
        textLabel7 = new QLabel(frame8);
        textLabel7->setObjectName(QStringLiteral("textLabel7"));
        textLabel7->setGeometry(QRect(21, 27, 62, 31));
        textLabel7->setWordWrap(false);
        ComboxDiskNo = new QComboBox(frame8);
        ComboxDiskNo->setObjectName(QStringLiteral("ComboxDiskNo"));
        ComboxDiskNo->setGeometry(QRect(84, 29, 80, 22));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette5.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette5.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette5.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush);
        palette5.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette5.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette5.setBrush(QPalette::Active, QPalette::Highlight, brush8);
        palette5.setBrush(QPalette::Active, QPalette::HighlightedText, brush6);
        palette5.setBrush(QPalette::Active, QPalette::Link, brush);
        palette5.setBrush(QPalette::Active, QPalette::LinkVisited, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        palette5.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette5.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette5.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Highlight, brush8);
        palette5.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::Link, brush10);
        palette5.setBrush(QPalette::Inactive, QPalette::LinkVisited, brush11);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::Midlight, brush9);
        palette5.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette5.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette5.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette5.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::Highlight, brush8);
        palette5.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::Link, brush10);
        palette5.setBrush(QPalette::Disabled, QPalette::LinkVisited, brush11);
        ComboxDiskNo->setPalette(palette5);
        TextDiskInfo = new QLabel(frame8);
        TextDiskInfo->setObjectName(QStringLiteral("TextDiskInfo"));
        TextDiskInfo->setGeometry(QRect(20, 60, 370, 22));
        TextDiskInfo->setWordWrap(false);
        textLabel8 = new QLabel(frame8);
        textLabel8->setObjectName(QStringLiteral("textLabel8"));
        textLabel8->setGeometry(QRect(170, 27, 61, 31));
        textLabel8->setWordWrap(false);
        ComboxOperateType = new QComboBox(frame8);
        ComboxOperateType->setObjectName(QStringLiteral("ComboxOperateType"));
        ComboxOperateType->setGeometry(QRect(233, 29, 151, 22));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette6.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette6.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette6.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette6.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush);
        palette6.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette6.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette6.setBrush(QPalette::Active, QPalette::Highlight, brush8);
        palette6.setBrush(QPalette::Active, QPalette::HighlightedText, brush6);
        palette6.setBrush(QPalette::Active, QPalette::Link, brush);
        palette6.setBrush(QPalette::Active, QPalette::LinkVisited, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        palette6.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette6.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette6.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Highlight, brush8);
        palette6.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::Link, brush10);
        palette6.setBrush(QPalette::Inactive, QPalette::LinkVisited, brush11);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::Midlight, brush9);
        palette6.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette6.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette6.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette6.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::Highlight, brush8);
        palette6.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::Link, brush10);
        palette6.setBrush(QPalette::Disabled, QPalette::LinkVisited, brush11);
        ComboxOperateType->setPalette(palette6);
        ButDiskControl = new QPushButton(frame8);
        ButDiskControl->setObjectName(QStringLiteral("ButDiskControl"));
        ButDiskControl->setGeometry(QRect(400, 25, 80, 30));
        frame10 = new QFrame(Dialog);
        frame10->setObjectName(QStringLiteral("frame10"));
        frame10->setGeometry(QRect(10, 237, 800, 40));
        frame10->setFrameShape(QFrame::StyledPanel);
        frame10->setFrameShadow(QFrame::Plain);
        ButBoot = new QPushButton(frame10);
        ButBoot->setObjectName(QStringLiteral("ButBoot"));
        ButBoot->setGeometry(QRect(10, 7, 82, 27));
        ButBoot_2 = new QPushButton(frame10);
        ButBoot_2->setObjectName(QStringLiteral("ButBoot_2"));
        ButBoot_2->setGeometry(QRect(120, 7, 181, 27));
        frame9 = new QFrame(Dialog);
        frame9->setObjectName(QStringLiteral("frame9"));
        frame9->setGeometry(QRect(10, 286, 800, 120));
        frame9->setFrameShape(QFrame::StyledPanel);
        frame9->setFrameShadow(QFrame::Plain);
        frame13 = new QFrame(frame9);
        frame13->setObjectName(QStringLiteral("frame13"));
        frame13->setGeometry(QRect(10, 10, 364, 65));
        frame13->setFrameShape(QFrame::StyledPanel);
        frame13->setFrameShadow(QFrame::Plain);
        ButNUM0 = new QPushButton(frame13);
        ButNUM0->setObjectName(QStringLiteral("ButNUM0"));
        ButNUM0->setGeometry(QRect(2, 3, 41, 60));
        ButNUM1 = new QPushButton(frame13);
        ButNUM1->setObjectName(QStringLiteral("ButNUM1"));
        ButNUM1->setGeometry(QRect(43, 3, 40, 31));
        ButNUM2 = new QPushButton(frame13);
        ButNUM2->setObjectName(QStringLiteral("ButNUM2"));
        ButNUM2->setGeometry(QRect(82, 3, 40, 31));
        ButNUM3 = new QPushButton(frame13);
        ButNUM3->setObjectName(QStringLiteral("ButNUM3"));
        ButNUM3->setGeometry(QRect(122, 3, 40, 31));
        ButNUM4 = new QPushButton(frame13);
        ButNUM4->setObjectName(QStringLiteral("ButNUM4"));
        ButNUM4->setGeometry(QRect(162, 3, 40, 31));
        ButNUM5 = new QPushButton(frame13);
        ButNUM5->setObjectName(QStringLiteral("ButNUM5"));
        ButNUM5->setGeometry(QRect(202, 3, 40, 31));
        ButNUM6 = new QPushButton(frame13);
        ButNUM6->setObjectName(QStringLiteral("ButNUM6"));
        ButNUM6->setGeometry(QRect(242, 3, 40, 31));
        ButNUM7 = new QPushButton(frame13);
        ButNUM7->setObjectName(QStringLiteral("ButNUM7"));
        ButNUM7->setGeometry(QRect(282, 3, 40, 31));
        ButNUM8 = new QPushButton(frame13);
        ButNUM8->setObjectName(QStringLiteral("ButNUM8"));
        ButNUM8->setGeometry(QRect(322, 3, 40, 31));
        ButNUM9 = new QPushButton(frame13);
        ButNUM9->setObjectName(QStringLiteral("ButNUM9"));
        ButNUM9->setGeometry(QRect(42, 33, 40, 30));
        ButNUM10 = new QPushButton(frame13);
        ButNUM10->setObjectName(QStringLiteral("ButNUM10"));
        ButNUM10->setGeometry(QRect(82, 33, 40, 30));
        ButNUM11 = new QPushButton(frame13);
        ButNUM11->setObjectName(QStringLiteral("ButNUM11"));
        ButNUM11->setGeometry(QRect(122, 33, 40, 30));
        ButNUM12 = new QPushButton(frame13);
        ButNUM12->setObjectName(QStringLiteral("ButNUM12"));
        ButNUM12->setGeometry(QRect(162, 33, 40, 30));
        ButNUM13 = new QPushButton(frame13);
        ButNUM13->setObjectName(QStringLiteral("ButNUM13"));
        ButNUM13->setGeometry(QRect(202, 33, 40, 30));
        ButNUM14 = new QPushButton(frame13);
        ButNUM14->setObjectName(QStringLiteral("ButNUM14"));
        ButNUM14->setGeometry(QRect(242, 33, 40, 30));
        ButNUM15 = new QPushButton(frame13);
        ButNUM15->setObjectName(QStringLiteral("ButNUM15"));
        ButNUM15->setGeometry(QRect(282, 33, 40, 30));
        ButNUM16 = new QPushButton(frame13);
        ButNUM16->setObjectName(QStringLiteral("ButNUM16"));
        ButNUM16->setGeometry(QRect(322, 33, 40, 30));
        frame14 = new QFrame(frame9);
        frame14->setObjectName(QStringLiteral("frame14"));
        frame14->setGeometry(QRect(10, 72, 364, 34));
        frame14->setFrameShape(QFrame::StyledPanel);
        frame14->setFrameShadow(QFrame::Plain);
        ButJmpDown = new QPushButton(frame14);
        ButJmpDown->setObjectName(QStringLiteral("ButJmpDown"));
        ButJmpDown->setGeometry(QRect(323, 2, 40, 30));
        ButJmpUp = new QPushButton(frame14);
        ButJmpUp->setObjectName(QStringLiteral("ButJmpUp"));
        ButJmpUp->setGeometry(QRect(283, 2, 40, 30));
        ButStop = new QPushButton(frame14);
        ButStop->setObjectName(QStringLiteral("ButStop"));
        ButStop->setGeometry(QRect(242, 2, 40, 30));
        ButNext = new QPushButton(frame14);
        ButNext->setObjectName(QStringLiteral("ButNext"));
        ButNext->setGeometry(QRect(202, 2, 40, 30));
        ButFast = new QPushButton(frame14);
        ButFast->setObjectName(QStringLiteral("ButFast"));
        ButFast->setGeometry(QRect(162, 2, 40, 30));
        ButPlay = new QPushButton(frame14);
        ButPlay->setObjectName(QStringLiteral("ButPlay"));
        ButPlay->setGeometry(QRect(122, 2, 40, 30));
        ButSlow = new QPushButton(frame14);
        ButSlow->setObjectName(QStringLiteral("ButSlow"));
        ButSlow->setGeometry(QRect(82, 2, 40, 30));
        ButPrew = new QPushButton(frame14);
        ButPrew->setObjectName(QStringLiteral("ButPrew"));
        ButPrew->setGeometry(QRect(41, 2, 42, 30));
        ButRec = new QPushButton(frame14);
        ButRec->setObjectName(QStringLiteral("ButRec"));
        ButRec->setGeometry(QRect(2, 2, 40, 30));
        frame15 = new QFrame(frame9);
        frame15->setObjectName(QStringLiteral("frame15"));
        frame15->setGeometry(QRect(374, 10, 46, 96));
        frame15->setFrameShape(QFrame::StyledPanel);
        frame15->setFrameShadow(QFrame::Plain);
        ButEsc = new QPushButton(frame15);
        ButEsc->setObjectName(QStringLiteral("ButEsc"));
        ButEsc->setGeometry(QRect(3, 3, 40, 31));
        ButFn1 = new QPushButton(frame15);
        ButFn1->setObjectName(QStringLiteral("ButFn1"));
        ButFn1->setGeometry(QRect(3, 33, 40, 30));
        ButFn2 = new QPushButton(frame15);
        ButFn2->setObjectName(QStringLiteral("ButFn2"));
        ButFn2->setGeometry(QRect(3, 63, 40, 30));
        ButSplit = new QPushButton(frame9);
        ButSplit->setObjectName(QStringLiteral("ButSplit"));
        ButSplit->setGeometry(QRect(657, 17, 40, 30));
        ButOne = new QPushButton(frame9);
        ButOne->setObjectName(QStringLiteral("ButOne"));
        ButOne->setGeometry(QRect(617, 17, 40, 30));
        ButInfo = new QPushButton(frame9);
        ButInfo->setObjectName(QStringLiteral("ButInfo"));
        ButInfo->setGeometry(QRect(577, 73, 40, 30));
        ButPower = new QPushButton(frame9);
        ButPower->setObjectName(QStringLiteral("ButPower"));
        ButPower->setGeometry(QRect(667, 62, 110, 40));
        ButPower->setFlat(false);
        ButAddr = new QPushButton(frame9);
        ButAddr->setObjectName(QStringLiteral("ButAddr"));
        ButAddr->setGeometry(QRect(617, 73, 40, 30));
        ButNine = new QPushButton(frame9);
        ButNine->setObjectName(QStringLiteral("ButNine"));
        ButNine->setGeometry(QRect(577, 17, 40, 31));
        frame16 = new QFrame(frame9);
        frame16->setObjectName(QStringLiteral("frame16"));
        frame16->setGeometry(QRect(420, 10, 151, 101));
        frame16->setFrameShape(QFrame::StyledPanel);
        frame16->setFrameShadow(QFrame::Plain);
        ButEnter = new QPushButton(frame16);
        ButEnter->setObjectName(QStringLiteral("ButEnter"));
        ButEnter->setGeometry(QRect(50, 37, 45, 30));
        ButUP = new QPushButton(frame16);
        ButUP->setObjectName(QStringLiteral("ButUP"));
        ButUP->setGeometry(QRect(50, 3, 45, 30));
        ButRight = new QPushButton(frame16);
        ButRight->setObjectName(QStringLiteral("ButRight"));
        ButRight->setGeometry(QRect(100, 37, 45, 30));
        ButLeft = new QPushButton(frame16);
        ButLeft->setObjectName(QStringLiteral("ButLeft"));
        ButLeft->setGeometry(QRect(3, 37, 41, 31));
        ButDown = new QPushButton(frame16);
        ButDown->setObjectName(QStringLiteral("ButDown"));
        ButDown->setGeometry(QRect(50, 70, 45, 30));

        retranslateUi(Dialog);

        ButPower->setDefault(true);


        QMetaObject::connectSlotsByName(Dialog);
    } // setupUi

    void retranslateUi(QDialog *Dialog)
    {
        Dialog->setWindowTitle(QApplication::translate("Dialog", "Device Control", Q_NULLPTR));
        textLabel1->setText(QApplication::translate("Dialog", "Net Trigger Alarm In", Q_NULLPTR));
        textLabel3->setText(QApplication::translate("Dialog", "Channel No.", Q_NULLPTR));
        ButAlarmInStart->setText(QApplication::translate("Dialog", "Start", Q_NULLPTR));
        ButAlarmInStop->setText(QApplication::translate("Dialog", "Stop", Q_NULLPTR));
        textLabel2->setText(QApplication::translate("Dialog", "Net Trigger Alarm Out", Q_NULLPTR));
        ButAlarmOutStart->setText(QApplication::translate("Dialog", "Start", Q_NULLPTR));
        ButAlarmOutStop->setText(QApplication::translate("Dialog", "Stop", Q_NULLPTR));
        textLabel3_2->setText(QApplication::translate("Dialog", "Channel No.", Q_NULLPTR));
        IP->setText(QApplication::translate("Dialog", "IP", Q_NULLPTR));
        Port->setText(QApplication::translate("Dialog", "Port", Q_NULLPTR));
        UserName->setText(QApplication::translate("Dialog", "User Name", Q_NULLPTR));
        PassWord->setText(QApplication::translate("Dialog", "PassWord", Q_NULLPTR));
        lineEdit1->setText(QApplication::translate("Dialog", "10.7.4.23", Q_NULLPTR));
        lineEdit2->setText(QApplication::translate("Dialog", "37777", Q_NULLPTR));
        lineEdit4->setText(QApplication::translate("Dialog", "admin", Q_NULLPTR));
        Logout->setText(QApplication::translate("Dialog", "Logout", Q_NULLPTR));
        Login->setText(QApplication::translate("Dialog", "Login", Q_NULLPTR));
        lineEdit3->setText(QApplication::translate("Dialog", "admin", Q_NULLPTR));
        textLabel4->setText(QApplication::translate("Dialog", "Calibrate DVR Time", Q_NULLPTR));
        textLabel5->setText(QApplication::translate("Dialog", "DateTime", Q_NULLPTR));
        ButGetTime->setText(QApplication::translate("Dialog", "Get", Q_NULLPTR));
        ButSetTime->setText(QApplication::translate("Dialog", "Set", Q_NULLPTR));
        textLabel6->setText(QApplication::translate("Dialog", "Storage Manage", Q_NULLPTR));
        textLabel7->setText(QApplication::translate("Dialog", "Disk NO.", Q_NULLPTR));
        TextDiskInfo->setText(QString());
        textLabel8->setText(QApplication::translate("Dialog", "Operate", Q_NULLPTR));
        ComboxOperateType->clear();
        ComboxOperateType->insertItems(0, QStringList()
         << QApplication::translate("Dialog", "clear data", Q_NULLPTR)
         << QApplication::translate("Dialog", "read & write", Q_NULLPTR)
         << QApplication::translate("Dialog", "read Only", Q_NULLPTR)
         << QApplication::translate("Dialog", "Redundant", Q_NULLPTR)
         << QApplication::translate("Dialog", "Error Recovery", Q_NULLPTR)
        );
        ButDiskControl->setText(QApplication::translate("Dialog", "Control", Q_NULLPTR));
        ButBoot->setText(QApplication::translate("Dialog", "Reboot", Q_NULLPTR));
        ButBoot_2->setText(QApplication::translate("Dialog", "Get SDK Version", Q_NULLPTR));
        ButNUM0->setText(QApplication::translate("Dialog", "0", Q_NULLPTR));
        ButNUM1->setText(QApplication::translate("Dialog", "1", Q_NULLPTR));
        ButNUM2->setText(QApplication::translate("Dialog", "2", Q_NULLPTR));
        ButNUM3->setText(QApplication::translate("Dialog", "3", Q_NULLPTR));
        ButNUM4->setText(QApplication::translate("Dialog", "4", Q_NULLPTR));
        ButNUM5->setText(QApplication::translate("Dialog", "5", Q_NULLPTR));
        ButNUM6->setText(QApplication::translate("Dialog", "6", Q_NULLPTR));
        ButNUM7->setText(QApplication::translate("Dialog", "7", Q_NULLPTR));
        ButNUM8->setText(QApplication::translate("Dialog", "8", Q_NULLPTR));
        ButNUM9->setText(QApplication::translate("Dialog", "9", Q_NULLPTR));
        ButNUM10->setText(QApplication::translate("Dialog", "10", Q_NULLPTR));
        ButNUM11->setText(QApplication::translate("Dialog", "11", Q_NULLPTR));
        ButNUM12->setText(QApplication::translate("Dialog", "12", Q_NULLPTR));
        ButNUM13->setText(QApplication::translate("Dialog", "13", Q_NULLPTR));
        ButNUM14->setText(QApplication::translate("Dialog", "14", Q_NULLPTR));
        ButNUM15->setText(QApplication::translate("Dialog", "15", Q_NULLPTR));
        ButNUM16->setText(QApplication::translate("Dialog", "16", Q_NULLPTR));
        ButJmpDown->setText(QApplication::translate("Dialog", "Jmp", Q_NULLPTR));
        ButJmpUp->setText(QApplication::translate("Dialog", "Jmp", Q_NULLPTR));
        ButStop->setText(QApplication::translate("Dialog", "Stop", Q_NULLPTR));
        ButNext->setText(QApplication::translate("Dialog", "Next", Q_NULLPTR));
        ButFast->setText(QApplication::translate("Dialog", "Fast", Q_NULLPTR));
        ButPlay->setText(QApplication::translate("Dialog", "Play", Q_NULLPTR));
        ButSlow->setText(QApplication::translate("Dialog", "Slow", Q_NULLPTR));
        ButPrew->setText(QApplication::translate("Dialog", "Prew", Q_NULLPTR));
        ButRec->setText(QApplication::translate("Dialog", "Rec", Q_NULLPTR));
        ButEsc->setText(QApplication::translate("Dialog", "Esc", Q_NULLPTR));
        ButFn1->setText(QApplication::translate("Dialog", "Fn1", Q_NULLPTR));
        ButFn2->setText(QApplication::translate("Dialog", "Fn2", Q_NULLPTR));
        ButSplit->setText(QApplication::translate("Dialog", "Split", Q_NULLPTR));
        ButOne->setText(QApplication::translate("Dialog", "One", Q_NULLPTR));
        ButInfo->setText(QApplication::translate("Dialog", "Info", Q_NULLPTR));
        ButPower->setText(QApplication::translate("Dialog", "Power", Q_NULLPTR));
        ButAddr->setText(QApplication::translate("Dialog", "Addr", Q_NULLPTR));
        ButNine->setText(QApplication::translate("Dialog", "Nine", Q_NULLPTR));
        ButEnter->setText(QApplication::translate("Dialog", "Enter", Q_NULLPTR));
        ButUP->setText(QApplication::translate("Dialog", "Up", Q_NULLPTR));
        ButRight->setText(QApplication::translate("Dialog", "Right", Q_NULLPTR));
        ButLeft->setText(QApplication::translate("Dialog", "Left", Q_NULLPTR));
        ButDown->setText(QApplication::translate("Dialog", "Down", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class Dialog: public Ui_Dialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_DIALOG_H
